skf:
  n_splits: 5
  shuffle: True
  random_state: 42

gscv:
  scoring: ["accuracy", "precision", "recall", "f1", "roc_auc"]
  refit: "f1"
  verbose: 3
  n_jobs: -1

grid:
  Random Forest:
    model__n_estimators: [100, 200, 300]
    model__max_depth: [None, 10, 25]
    model__min_samples_split: [2, 5, 10]
  Logistic Regression:
    model__C: [0.001, 0.01, 0.1, 1, 10, 100]
    model__solver: ['newton-cg', 'lbfgs', 'liblinear']
    model__max_iter: [100, 200, 500]
  Gradient Boosting:
    model__learning_rate: [0.02, 0.1]
    model__min_samples_split: [0.5, 2, 5]
    model__min_samples_leaf: [0.2, 1, 5]
    model__max_depth: [5, 15, 30]
    model__n_estimators: [100, 200, 300]