apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-insurance-deployment
  labels:
    app: ai-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-insurance
  template:
    metadata:
      labels:
        app: ai-insurance
    spec:
      containers:
      - name: ai-insurance
        image: jbrable/ai_insurance:v2.0.4
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: "3Gi"
              cpu: "3000m"
            requests:
              memory: "100Mi"
              cpu: "1000m"
          
