apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-insurance-deployment
  labels:
    app: ai-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-insurance
  template:
    metadata:
      labels:
        app: ai-insurance
    spec:
      containers:
      - name: ai-insurance
        image: jbrable/ai_insurance:v1.0.1
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: "30Gi"
              cpu: "30000m"
